<?php
require_once("head.php");
require_once("header.php");
require_once("sidebar.php");
if($_REQUEST["page"]){
    $page=$_REQUEST["page"];
    require_once($page);
}
else{
    require_once("body.php");
}
require_once("footer.php");
?>